rules = [
  OrganizeImports,
  DisableSyntax,
  scala-009,
  scala-010,
  scala-011
]

OrganizeImports {
  removeUnused = true
}

DisableSyntax {
  noVars = false   // allow vars in tests
  noNulls = true
}
