rules = [
  OrganizeImports
  DisableSyntax
  scala-007
  scala-009
  scala-010
  scala-011
  scala-027
]

OrganizeImports {
  removeUnused = true
}

DisableSyntax {
  noVars = false   // allow vars in tests
  noNulls = true
}
