// Generated by CIRCT firtool-1.47.0
module Dff(
  input  clock,
         reset,
         io_d,
         io_enable,
  output io_q
);

  reg q;
  always @(posedge clock) begin
    if (reset)
      q <= 1'h0;
    else if (io_enable)
      q <= io_d;
  end // always @(posedge)
  assign io_q = q;
endmodule

